"""Deploy only notebooks to the CAE Fabric workspace via fabric-cicd.

Reads `.deploy-secrets.json` (gitignored) and writes a fresh
`workspace/parameter.yml` so fabric-cicd's find_replace re-injects
connection strings / agent config on every deploy.
"""
import json
from pathlib import Path

from fabric_cicd import FabricWorkspace, publish_all_items
from azure.identity import AzureCliCredential

WORKSPACE_ID = "161c43a4-6a14-4b8f-81eb-070f0981a609"
ENVIRONMENT = "dev"
REPO_ROOT = Path(__file__).resolve().parent
WORKSPACE_DIR = REPO_ROOT / "workspace"
SECRETS_FILE = REPO_ROOT / ".deploy-secrets.json"
PARAM_FILE = WORKSPACE_DIR / "parameter.yml"

# Maps placeholder token in notebook source -> key in .deploy-secrets.json,
# scoped to the notebooks that contain that placeholder.
REPLACEMENTS = [
    {
        "placeholder": "<<TELEMETRY_EVENTSTREAM_CONNECTION_STRING>>",
        "secret_key": "TELEMETRY_EVENTSTREAM_CONNECTION_STRING",
        "item_names": ["TelemetryFaultInjection", "SimulatorTelemetryEmulator"],
    },
    {
        "placeholder": "<<CLOCKIN_EVENTSTREAM_CONNECTION_STRING>>",
        "secret_key": "CLOCKIN_EVENTSTREAM_CONNECTION_STRING",
        "item_names": ["ClockInEventEmulator"],
    },
    {
        "placeholder": "<<FOUNDRY_AGENT_PROJECT_ENDPOINT>>",
        "secret_key": "FOUNDRY_AGENT_PROJECT_ENDPOINT",
        "item_names": ["AlertNotificationAgent", "AnomalyDetection"],
    },
    {
        "placeholder": "<<FOUNDRY_AGENT_ID>>",
        "secret_key": "FOUNDRY_AGENT_ID",
        "item_names": ["AlertNotificationAgent", "AnomalyDetection"],
    },
    {
        "placeholder": "<<TEAMS_WEBHOOK_URL>>",
        "secret_key": "TEAMS_WEBHOOK_URL",
        "item_names": ["AlertNotificationAgent"],
    },
]


def _yaml_escape(value: str) -> str:
    """Return a YAML-safe double-quoted scalar."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_parameter_yml() -> None:
    if not SECRETS_FILE.exists():
        raise FileNotFoundError(
            f"{SECRETS_FILE} not found. Copy .deploy-secrets.example.json and fill in values."
        )
    secrets = json.loads(SECRETS_FILE.read_text(encoding="utf-8"))

    lines = [
        "# Auto-generated by _deploy_notebooks.py from .deploy-secrets.json.",
        "# Do not edit by hand; values come from .deploy-secrets.json (gitignored).",
        "find_replace:",
    ]
    for entry in REPLACEMENTS:
        value = secrets.get(entry["secret_key"], "")
        if not value:
            print(f"  skip {entry['placeholder']} (empty in secrets)")
            continue
        lines.append(f"  - find_value: {_yaml_escape(entry['placeholder'])}")
        lines.append(f"    replace_value:")
        lines.append(f"      {ENVIRONMENT}: {_yaml_escape(value)}")
        lines.append(f"    item_type:")
        lines.append(f"      - \"Notebook\"")
        lines.append(f"    item_name:")
        for name in entry["item_names"]:
            lines.append(f"      - {_yaml_escape(name)}")

    PARAM_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {PARAM_FILE}")


write_parameter_yml()

ws = FabricWorkspace(
    workspace_id=WORKSPACE_ID,
    environment=ENVIRONMENT,
    repository_directory=str(WORKSPACE_DIR),
    item_type_in_scope=["Notebook"],
    token_credential=AzureCliCredential(),
)
print(f"Publishing notebooks to workspace {WORKSPACE_ID} (env={ENVIRONMENT}) ...")
publish_all_items(ws)
print("Done.")
